# ---------- Build ----------
FROM node:20-alpine AS builder

WORKDIR /app


COPY package*.json ./
RUN npm install


COPY . .


RUN npm run build


# ---------- Runtime ----------
FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/data ./data

# puerto
EXPOSE 4000

# ejecutar app
CMD ["node", "dist/main.js"]
